apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: publisher-system

spec:
  selector:
    app: jobs

  type: ClusterIP

  ports:
    - name: jobs-api
      port: 3000
      targetPort: jobs-api
    - name: jobs-api-debug
      port: 4000
      targetPort: jobs-api-debug