apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-pod
  namespace: publisher-system

spec:
  selector:
    matchLabels:
      app: jobs

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: jobs

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: jobs-api
          #image: jobs-api-image # place holder for actual image name
          resources:
            requests:
              cpu: "1500m" # I need access to 1.5 core on the node.
              memory: 500Mi
            limits:
              cpu: "1500m" # Execute instructions 150ms/200ms on my 1.5 core.
              memory: 500Mi
