apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-pod
  namespace: publisher-system

spec:
  selector:
    matchLabels:
      app: jobs

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: jobs

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: jobs-api
          image: jobs-api-image # place holder for actual image name
