apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/jobs/
patches:
  - path: ./dev-jobs-patch-deploy.yaml
images:
  - name: jobs-api-image
    newName: publisher/service/jobs-api
    newTag: 0.0.1
