apiVersion: v1
kind: Namespace
metadata:
  name: publisher-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-pod # Deployment name
  namespace: publisher-system

spec:
  selector:
    matchLabels:
      app: jobs # Selector for POD name search
  template:
    metadata:
      labels:
        app: jobs
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60

      containers:
        - name: jobs-api
          image: jobs-api-image # place holder for actual image name

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
